server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/baza_de_date_angajati
        username: root
        password: admin
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect